name: ci-user-service

on:
  workflow_dispatch:
  pull_request:
    branches: ["develop"]

jobs:
  run-test-and-code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Download modules
        run: |
          go mod tidy
          go mod download

      - name: Run Test and Generate Coverage Report
        run: |
          go clean -testcache
          go test ./... -coverprofile=coverage.out -coverpkg=./...

      - name: Sonarqube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
